---
apiVersion: v1
kind: List
items:
  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        app: matches
        stack: echo
        interface: rest
        language: golang
      name: matches
    spec:
      ports:
        - name: http
          port: 9999
          protocol: TCP
          targetPort: 9999
      selector:
        app: matches
  - apiVersion: extensions/v1beta1
    kind: Deployment
    metadata:
      labels:
        version: v1
        app: matches
      name: matches
    spec:
      replicas: 1
      revisionHistoryLimit: 2
      selector:
        matchLabels:
          app: matches
          stack: echo
          interface: rest
          language: golang
      template:
        metadata:
          labels:
            app: matches
            version: v1
            stack: echo
            interface: rest
            language: golang
        spec:
          containers:
            - image: gcr.io/mvp-mesh-pre-testing/match:latest
              imagePullPolicy: Always
              resources:
                requests:
                  memory: "5Mi"
                  cpu: "50m"
                limits:
                  memory: "10Mi"
                  cpu: "100m"
              livenessProbe:
                httpGet:
                  path: /health
                  port: 9999
                  scheme: HTTP
                initialDelaySeconds: 1
              name: matches
              ports:
                - containerPort: 9999
                  name: http
                  protocol: TCP
              readinessProbe:
                httpGet:
                  path: /health
                  port: 9999
                  scheme: HTTP
                initialDelaySeconds: 1
              securityContext:
                privileged: false